server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: Kafka

  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    consumer:
      group-id: ${GROUP_ID:group-1}
      auto-offset-reset: earliest # start from beginning
#      auto-offset-reset: latest # start from new incoming messages
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

