server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: Kafka

  kafka:
    bootstrap-servers:
      - localhost:9095
      - localhost:9096
      - localhost:9097
    consumer:
      group-id: ${GROUP_ID:group-1}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

